version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:80"
    depends_on:
      - db
      - localstack
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      AWS_REGION: ${AWS_REGION}
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      DEFAULT_REGION: ${AWS_REGION}
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d

volumes:
  pgdata:
  localstack_data:
