version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
      - localstack
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: userdb
      AWS_REGION: us-east-1
      SQS_QUEUE_URL: http://localstack:4566/000000000000/dataflow-queue

  db:
    image: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d

volumes:
  pgdata:
  localstack_data:

